name: Deploy to Heroku game-pit-poztman-server
'on':
  workflow_dispatch:
  push:
    branches:
      - poztman-server
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "game-pit-poztman-server"
          heroku_email: "sfktrkl@gmail.com"
